# Generated by Django 3.2.8 on 2021-10-21 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
