# Generated by Django 3.2.8 on 2021-10-22 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_rename_customer_order_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
    ]
