# Generated by Django 3.2.8 on 2021-10-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20211018_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='course',
            field=models.CharField(choices=[('Tunisia Food', 'Tunisia Food'), ('Ghana Food', 'Ghana Food'), ('Somalian Food', 'Somalian Food'), ('Kenyan Food', 'Kenyan Food'), ('Food', 'Food')], max_length=50),
        ),
    ]
