# Generated by Django 3.2.8 on 2021-10-18 08:20

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_alter_food_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='image',
            field=cloudinary.models.CloudinaryField(default=django.utils.timezone.now, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
