# Generated by Django 3.2.8 on 2021-10-19 08:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0008_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pexels.com%2Fsearch%2Ffood%2F&psig=AOvVaw0VgUuHvQN-B8K6F78vUMB3&ust=1634716899602000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCNjbh5OB1vMCFQAAAAAdAAAAABAD', max_length=255, verbose_name='image'),
        ),
    ]
