# Generated by Django 3.2.8 on 2021-10-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0011_auto_20211021_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
    ]
