# Generated by Django 3.2.8 on 2021-10-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0014_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
