# Generated by Django 3.2.8 on 2021-10-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0016_alter_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_boy',
        ),
    ]
