# Generated by Django 3.2.8 on 2021-10-22 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0017_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
